apiVersion: v1
kind: Pod
metadata:
  labels:
    run: apache
  name: apache
spec:
  volumes:
  - name: vol-log
    emptyDir: {}
  - name: vol-cm-fluentd
    configMap:
      name: fluentd
  containers:
  - name: apache
    image: mingrammer/flog
    args:
    - -f
    - apache_combined
    - -n
    - "360"
    - -d
    - 5s
    - -t
    - log
    - -o
    - /log/apache.log
    volumeMounts:
    - name: vol-log
      mountPath: /log
  - name: log-collector
    image: treekat71/fluentd-s3
    env:
    - name: FLUENTD_CONF
      value: fluentd.conf
    volumeMounts:
    - name: vol-log
      mountPath: /log
      readOnly: true
    - name: vol-cm-fluentd
      mountPath: /fluentd/etc
      readOnly: true